machines:
  default:
    ssh_username: slaguna
    port_number: 8086
    staging_dir: /data/slaguna/sandbox/IBMFL/test_pendulum
    ibmfl_dir: /data/slaguna/repos/IBMFL
    venv_dir: .venv
    venv_uses_conda: False
  syl2:
    ip_address: 9.192.210.210
    port_number: 5000
  syl15:
    ip_address: 9.192.210.24
  syl23:
    ip_address: 9.192.244.87
  syl24:
    ip_address: 9.192.244.33
  syl25:
    ip_address: 9.192.244.60
  syl7:
    ip_address: 9.192.211.139

experiments:
  - local_staging_dir: /home/sean/sandbox/IBMFL/test_pendulum
    local_ibmfl_dir: /home/sean/repos/IBMFL_new/IBMFL
    agg_machine: syl23
    n_parties: 2
    party_machines: [ syl24, syl25 ]
    shuffle_party_machines: False
    n_trials: 2
    n_rounds: 5
    postproc_fn: gen_reward_vs_time_plots
    postproc_x_key: 'post_train:ts'
    postproc_y_keys: [
      'post_train:train:episode_reward_mean',
      'post_train:train:episode_reward_max',
      'post_train:eval:episode_reward_mean'
    ]
