connection:
  info:
    ip: ${agg_ip}
    port: ${agg_port}
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
fusion:
  name: RLFusionHandler
  path: ibmfl.aggregator.fusion.rl_avg_fusion_handler
hyperparams:
  global:
    num_parties: ${n_parties}
    rounds: ${n_rounds}
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
